### ISSUE TITLE
Implement interface for JSON patch

### ISSUE THREAD

**Issue by gpestana** [gpestana/rdoc#23]
[JSON patch](https://github.com/evanphx/json-patch) creates and applies patches for JSON data structures. This library seems to be a good fit to provide a high-level interface for developers to use rdoc.

**tasks**
- [ ] Define API merging and manipulating rdoc structures
- [ ] Create and apply JSON merge (https://github.com/evanphx/json-patch#create-and-apply-a-merge-patch)
- [ ] Docs update + add examples
